# currently a placeholder. Will be implemented fully
# after the zeek -> splunk pipeline is finished. 


version: '3.8'

services:
  zeek:
    image: zeek/zeek:lts
    volumes:
      - ./pcaps:/pcaps:ro
      - ./logs:/logs
    working_dir: /logs
    entrypoint: ["zeek"]
    command: ["-C", "-r", "/pcaps/sample.pcap"]
    environment:
      - TZ=UTC

  processor:
    build: ./processor
    ports:
      - "8001:8001"
    environment:
      - SPLUNK_HOST=splunk
      - SPLUNK_PORT=8088
      - SPLUNK_TOKEN=${SPLUNK_TOKEN}
      - SPLUNK_INDEX=main
    volumes:
      - ./logs:/app/logs:ro
    depends_on:
      - splunk
    restart: unless-stopped

  splunk:
    image: splunk/splunk:9.4.2
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=${SPLUNK_PASSWORD}
      - TZ=UTC
    ports:
      - "8000:8000"
      - "8088:8088"
    volumes:
      - splunk-var:/opt/splunk/var
      - ./logs:/opt/splunk/etc/logs

volumes:
  splunk-var: